export const GET_TABLE_DATA = 'GET_TABLE_DATA';
export const SET_CURRENT = 'SET_CURRENT';
export const CHANGE_SORT_TYPE = 'CHANGE_SORT_TYPE';
export const SET_SEARCH_BY = 'SET_SEARCH_BY';
export const SET_ACTUAL_PAGE = 'SET_ACTUAL_PAGE';
export const UPDATE_ITEMS = 'UPDATE_ITEMS';
